---
homelab_root: /opt/homelab
docker_network_name: main_network

# Paths mirrored from prod compose bind-mounts; created only when homelab_env == lab
lab_host_bind_paths:
  - /mnt/HomelabData/storageDir
  - /mnt/HomelabData/notesData
  - /mnt/HomelabData/homelab-backup
  - /home/ubuntu/appdata

homelab_stacks:
  - nginx-proxy-manager
  - hashicorp-vault
  - mysql-phpmyadmin
  - postgres-pgvector
  - ollama
  - jenkins
  - cadvisor
  - it-tools
  - omni-tools
  - filebrowser-quantum
  - stirling-pdf
  - trilium-notes
  - dashboard
  - redis
  - backup-system
