services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    networks:
      - main_network
    ports:
      - '7070:8080'
    volumes:
      - ./configs:/configs
    restart: unless-stopped

networks:
  main_network:
    external: true
