all:
  children:
    homelab:
      hosts:
        homelab-lab:
          ansible_host: __LAB_HOST__
          ansible_user: __LAB_USER__
          ansible_become_password: __LAB_ROOT_PASSWORD__
          ansible_pipelining: false
          ansible_python_interpreter: auto_silent
      vars:
        homelab_env: lab
        keepass_group: lab
