---
- name: List existing NPM proxy hosts
  ansible.builtin.uri:
    url: "{{npm_api_url}}/nginx/proxy-hosts"
    method: GET
    headers:
      Authorization: "Bearer {{npm_api_token}}"
    status_code: 200
    timeout: "{{npm_api_timeout}}"
  register: npm_proxy_hosts_list
  no_log: true

- name: Ensure each desired proxy hosts
  ansible.builtin.include_tasks: npm-ensure-one-proxy-host.yml
  loop: "{{npm_desired_hosts}}"
  loop_control:
    loop_var: desired_host
    label: "{{desired_host.name | default(desired_host.domain_names[0])}}"
