services:
    mysql:
        container_name: main_db
        networks:
            - main_network
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=Ziomal1245
        image: mysql
        restart: unless-stopped
        volumes:
            - ./mysql_data:/var/lib/mysql

    phpmyadmin:
        container_name: phpadmin
        restart: unless-stopped
        depends_on:
            - mysql
        networks:
            - main_network
        ports:
            - "8087:80"
        environment:
            - PMA_ARBITRARY=1
        image: phpmyadmin

networks:
    main_network:
        external: true
